source 'https://cdn.cocoapods.org/' # 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'THSegmentedPagerExample' do
  pod 'HMSegmentedControl', '~> 1.5.6' # Thomas Bechtum 06-OCT-20 , '~> 1.5.2'
  pod 'THSegmentedPager', :path=> '../../THSegmentedPager'
end

# target 'THSegmentedPagerExampleTests' do # , :exclusive => true
#  pod 'FBSnapshotTestCase/Core'
#  pod 'Expecta+Snapshots'
#  pod 'Specta'
#  pod 'Expecta'
# end
